// utils/prefectures.ts
export type Prefecture = {
    name: string;
    shortName: string;
    englishName: string;
};

export const prefectures: Prefecture[] = [
    { name: "北海道", shortName: "北海道", englishName: "Hokkaido" },
    { name: "青森県", shortName: "青森", englishName: "Aomori" },
    { name: "岩手県", shortName: "岩手", englishName: "Iwate" },
    { name: "宮城県", shortName: "宮城", englishName: "Miyagi" },
    { name: "秋田県", shortName: "秋田", englishName: "Akita" },
    { name: "山形県", shortName: "山形", englishName: "Yamagata" },
    { name: "福島県", shortName: "福島", englishName: "Fukushima" },
    { name: "茨城県", shortName: "茨城", englishName: "Ibaraki" },
    { name: "栃木県", shortName: "栃木", englishName: "Tochigi" },
    { name: "群馬県", shortName: "群馬", englishName: "Gunma" },
    { name: "埼玉県", shortName: "埼玉", englishName: "Saitama" },
    { name: "千葉県", shortName: "千葉", englishName: "Chiba" },
    { name: "東京都", shortName: "東京", englishName: "Tokyo" },
    { name: "神奈川県", shortName: "神奈川", englishName: "Kanagawa" },
    { name: "新潟県", shortName: "新潟", englishName: "Niigata" },
    { name: "富山県", shortName: "富山", englishName: "Toyama" },
    { name: "石川県", shortName: "石川", englishName: "Ishikawa" },
    { name: "福井県", shortName: "福井", englishName: "Fukui" },
    { name: "山梨県", shortName: "山梨", englishName: "Yamanashi" },
    { name: "長野県", shortName: "長野", englishName: "Nagano" },
    { name: "岐阜県", shortName: "岐阜", englishName: "Gifu" },
    { name: "静岡県", shortName: "静岡", englishName: "Shizuoka" },
    { name: "愛知県", shortName: "愛知", englishName: "Aichi" },
    { name: "三重県", shortName: "三重", englishName: "Mie" },
    { name: "滋賀県", shortName: "滋賀", englishName: "Shiga" },
    { name: "京都府", shortName: "京都", englishName: "Kyoto" },
    { name: "大阪府", shortName: "大阪", englishName: "Osaka" },
    { name: "兵庫県", shortName: "兵庫", englishName: "Hyogo" },
    { name: "奈良県", shortName: "奈良", englishName: "Nara" },
    { name: "和歌山県", shortName: "和歌山", englishName: "Wakayama" },
    { name: "鳥取県", shortName: "鳥取", englishName: "Tottori" },
    { name: "島根県", shortName: "島根", englishName: "Shimane" },
    { name: "岡山県", shortName: "岡山", englishName: "Okayama" },
    { name: "広島県", shortName: "広島", englishName: "Hiroshima" },
    { name: "山口県", shortName: "山口", englishName: "Yamaguchi" },
    { name: "徳島県", shortName: "徳島", englishName: "Tokushima" },
    { name: "香川県", shortName: "香川", englishName: "Kagawa" },
    { name: "愛媛県", shortName: "愛媛", englishName: "Ehime" },
    { name: "高知県", shortName: "高知", englishName: "Kochi" },
    { name: "福岡県", shortName: "福岡", englishName: "Fukuoka" },
    { name: "佐賀県", shortName: "佐賀", englishName: "Saga" },
    { name: "長崎県", shortName: "長崎", englishName: "Nagasaki" },
    { name: "熊本県", shortName: "熊本", englishName: "Kumamoto" },
    { name: "大分県", shortName: "大分", englishName: "Oita" },
    { name: "宮崎県", shortName: "宮崎", englishName: "Miyazaki" },
    { name: "鹿児島県", shortName: "鹿児島", englishName: "Kagoshima" },
    { name: "沖縄県", shortName: "沖縄", englishName: "Okinawa" },
];

export const populationOrder: { [key: string]: number } = {
    "東京都": 1,
    "神奈川県": 2,
    "大阪府": 3,
    "愛知県": 4,
    "埼玉県": 5,
    "千葉県": 6,
    "兵庫県": 7,
    "北海道": 8,
    "福岡県": 9,
    "静岡県": 10,
    "茨城県": 11,
    "広島県": 12,
    "京都府": 13,
    "宮城県": 14,
    "新潟県": 15,
    "長野県": 16,
    "岐阜県": 17,
    "栃木県": 18,
    "群馬県": 19,
    "三重県": 20,
    "岡山県": 21,
    "福島県": 22,
    "山口県": 23,
    "愛媛県": 24,
    "熊本県": 25,
    "石川県": 26,
    "長崎県": 27,
    "大分県": 28,
    "宮崎県": 29,
    "鹿児島県": 30,
    "沖縄県": 31,
    "山梨県": 32,
    "秋田県": 33,
    "滋賀県": 34,
    "山形県": 35,
    "奈良県": 36,
    "香川県": 37,
    "和歌山県": 38,
    "鳥取県": 39,
    "富山県": 40,
    "高知県": 41,
    "島根県": 42,
    "佐賀県": 43,
    "福井県": 44,
    "徳島県": 45,
    "青森県": 46,
    "岩手県": 47,
};
